### ISSUE TITLE
API version header is not being set correctly

### ISSUE THREAD

**Issue by ryanwood** [stripe-contrib/stripe-cli#11]
Using the lastest version of stripe-cli (1.6.7) and stripe-ruby (1.20.1)

```
∴ stripe refund list -c ch_*************** -v "2015-02-18" -k sk_live_***************
.../gems/stripe-1.20.1/lib/stripe/stripe_object.rb:174:in `method_missing': undefined method `refunds' for #<Stripe::Charge:0x007ffaf3470f68> (NoMethodError)
	from .../gems/stripe-cli-1.6.7/lib/stripe/cli/commands/refunds.rb:16:in `list'
```

I confirmed this error is from the account's default API version setting being a very old version.

However when using curl with the same params it works:

```
∴ curl https://api.stripe.com/v1/charges/ch_***************/refunds\?limit\=3 \
   -u sk_live_**************: \
   -H "Stripe-Version: 2015-02-18"
{
  "object": "list",
  "has_more": false,
  "url": "/v1/charges/ch_***************/refunds",
  "data": [
    {
      "id": "re_***************",
      "amount": 109500,
      "currency": "usd",
      "created": 1400788393,
      "object": "refund",
      "balance_transaction": "txn_***************",
      "metadata": {},
      "charge": "ch_***************",
      "receipt_number": null,
      "reason": null
    }
  ]
}
```

Another example using the stripe-ruby gem directly works as well:

```
irb(main):001:0> Stripe.api_version
=> nil
irb(main):002:0> Stripe.api_version = "2015-02-16"
=> "2015-02-16"
irb(main):003:0> Stripe::Charge.retrieve('ch_***************', 'sk_live_***************').refunds.all
=> #<Stripe::ListObject:0x3fbf7925ccf4> JSON: {
  "object": "list",
  "has_more": false,
  "url": "/v1/charges/ch_***************/refunds",
  "data": [
    {"id":"re_***************","amount":109500,"currency":"usd","created":1400788393,"object":"refund","balance_transaction":"txn_***************","metadata":{},"charge":"ch_***************","receipt_number":null,"reason":null}
  ]
}

```

It seems that the Stripe API version header is not being set correctly.

**Comment by OutlawAndy** [comment]
Hi Ryan, sorry that this is giving you problems.

Yes, that no method error suggests an API version prior to charge objects being returned with a "refunds" property.

So far, I have been unable to reproduce this error in my own environment.  I will continue to dig into this and see what I can find.

One way that you could confirm if the API version header is indeed being sent incorrectly would be to check the log in your Stripe dashboard.

You can confirm that a request came from the Stripe-CLI gem by examining the "source" attribute of a log entry within your Stripe dashboard.

should look something like this:

![stripe-dashboard](https://cloud.githubusercontent.com/assets/1504753/6535821/8480a4d0-c40d-11e4-940e-d6ce2c1e534e.png)

please let me know what you find and I'll keep you posted on my progress as well.

Thanks,

-Andy

**Comment by ryanwood** [comment]
Thanks for confirming. After some more research it looks like it may have been a problem with the account data being old. I tried with another account and it works as expected. Great project.
