### ISSUE TITLE
Feature: support expansions

### ISSUE THREAD

**Issue by ryanwood** [stripe-contrib/stripe-cli#12]
Do you have any plans to support expandable attributes?

https://stripe.com/docs/api#expanding_objects

**Comment by OutlawAndy** [comment]
Hey Ryan,
Thanks for the suggestion.  I guess I've never really used them personally, so it just hadn't occurred to me before.  However, It seems like a great feature.

I've taken a quick look at the docs and run a couple tests.  I believe I can add this feature with just a couple lines of code.

I should have some time this week to patch it in and make sure it doesn't break anything.

**Comment by ryanwood** [comment]
@OutlawAndy That's great to hear. I started looking into a PR to make it happen but it would take me a bit longer. This would be a great addition to project. Looking forward to it.

**Comment by OutlawAndy** [comment]
Hey @ryanwood, the hold up here is an inconsistency within the Stripe-Ruby API where `#retrieve` works differently on `ListObject` then it does on `StripeObject`.  I just submitted a pull request to stripe-ruby that resolves this.  If its not accepted, I can work around it.  I would just prefer to stick with the 2 lines of code I mentioned before.  After all, when adding complexity, I always prefer to add it to someone else's code base. ;-)

Anyway, I just wanted to let you know that I haven't forgotten about this

**Comment by ryanwood** [comment]
@OutlawAndy I was checking in a few days ago and saw that. I definitely think that's the right move. No hurry on my part. Thanks!

**Comment by ryanwood** [comment]
@OutlawAndy Wondering if there was any progress on this?

**Comment by OutlawAndy** [comment]
@ryanwood I still haven't received any feedback on the issue I opened with stripe-ruby or the pull request I submitted to fix it.  I left another comment over there just now, but I honestly don't know if anyone has ever looked at it or even has it on their radar.  Perhaps, if you were to comment as well they would take note that there is interest in it (stripe/stripe-ruby#230).  I have a very simple patch for this feature ready to merge into stripe-cli, if and when stripe-ruby resolves the inconsistency with `ListObject`.  Thanks Ryan

**Comment by ryanwood** [comment]
@OutlawAndy Done. Hopefully they'll get that merged. Thanks again.

**Comment by OutlawAndy** [comment]
@ryanwood

Thanks for doing that!  I was able to get this merged into Stripe-Ruby today.  I'll still have to wait for them to push a new gem version before it can be used here, but I'll keep an eye on it and hopefully they'll do that very soon.  Thanks for all your help!

**Comment by OutlawAndy** [comment]
@ryanwood  it's in, finally! woohoo!

**Comment by ryanwood** [comment]
@OutlawAndy That's great! Thanks for the help.
