### ISSUE TITLE
add --no-strip-nils

### ISSUE THREAD

**Issue by nonchip** [stripe-contrib/stripe-cli#24]
as the inverse of `--strip-nils`, because as with dollar/cent one might to enable it globally but then temporarily switch back.

**Comment by OutlawAndy** [comment]
There is a global `--no-strip-nils` command line option.  Are you experiencing issues with it?

**Comment by nonchip** [comment]
just that I didn't know about it since it's undocumented :D

**Comment by OutlawAndy** [comment]
Okay, thank you.  I'll try making the documentation more explicate in the future.
